### ISSUE TITLE
Form doesn't work without Name field

### ISSUE THREAD

**Issue by RyanEwen** [MikeIbberson/bambora-material-ui#14]
Hi again - sorry to be a pain in your side. 

I noticed that the form doesn't work without a `<Name />` due to the use of `cardholder: nameInput.value` in `remoteForm.current.createToken`.

Also when there is a `<Name />` I see console errors about strings being passed instead of booleans for the error property.

**Comment by MikeIbberson** [comment]
No problem! I'll refactor the callback to conditionally include the cardholder name and I'll fix up the prop types to suppress the errors you're seeing in development.

**Comment by MikeIbberson** [comment]
This should be fixed in the most recent version. I'm closing the ticket now, but I can re-open if needed.
